name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into VM and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $SSH_USERNAME@$SSH_HOST << EOF
            cd ~/domostroi

            echo "MONGODB_URI=$MONGODB_URI" > .env.production
            echo "JWT_SECRET=$JWT_SECRET" >> .env.production

            cat .env.production

            sudo docker stop domostroi || true
            sudo docker rm domostroi || true
            git pull origin master
            docker build -f Dockerfile.production -t domostroi .
            sudo docker run -d -p 2056:3000 --name domostroi domostroi
          EOF
